
DELETE http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons

###
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{   
    "name": "aaaaaa",
    "number": "12345678",
    "id": "63b3d420f39bf55c978bcbfe"
}

